FROM ubuntu:16.04

ENV DEBIAN_FRONTEND=noninteractive
RUN sed -i s@archive.ubuntu.com@mirrors.ustc.edu.cn@g /etc/apt/sources.list
RUN apt-get update

# install basic libs
RUN apt-get -y install vim sudo
RUN apt-get -y remove x264 libx264-dev
RUN apt-get -y install build-essential checkinstall cmake pkg-config yasm
RUN apt-get -y install git gfortran
RUN apt-get -y install libjpeg8-dev libjasper-dev libpng12-dev
RUN apt-get -y install libtiff5-dev
RUN apt-get -y install libtiff-dev
RUN apt-get -y install libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev
RUN apt-get -y install libxine2-dev libv4l-dev
RUN apt-get -y install libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev
RUN apt-get -y install libgtk2.0-dev libtbb-dev qt5-default
RUN apt-get -y install libatlas-base-dev
RUN apt-get -y install libfaac-dev libmp3lame-dev libtheora-dev
RUN apt-get -y install libvorbis-dev libxvidcore-dev
RUN apt-get -y install libopencore-amrnb-dev libopencore-amrwb-dev
RUN apt-get -y install libavresample-dev
RUN apt-get -y install x264 v4l-utils
RUN apt-get -y install libprotobuf-dev protobuf-compiler
RUN apt-get -y install libgoogle-glog-dev libgflags-dev
RUN apt-get -y install libgphoto2-dev libeigen3-dev libhdf5-dev doxygen

RUN apt-get -y install python3-dev python3-pip python3-venv

RUN sh -c 'echo "deb http://mirrors.tuna.tsinghua.edu.cn/ros/ubuntu/ xenial main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

RUN apt-get update

RUN apt-get -y install ros-kinetic-desktop

RUN groupadd -g 1000 ubuntu
RUN useradd -g 1000 -u 1000 -m -s /bin/bash ubuntu
RUN usermod -aG sudo ubuntu
RUN echo "%sudo  ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/nopasswd

USER ubuntu:ubuntu
ENV HOME /home/ubuntu

WORKDIR ${HOME}

RUN echo 'source /opt/ros/kinetic/setup.bash' >> ${HOME}/.bashrc

# docker run -it --rm -v /tmp/.X11-unix:/tmp/.X11-unix 
# -e DISPLAY=$DISPLAY -h $HOSTNAME -v $HOME/.Xauthority:/home/ubuntu/.Xauthority 
# -v $HOME/carto_ws:/home/ubuntu/catkin_ws docker/ros:v1
